name: projeto_topicos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  file_picker: ^10.1.9
  firebase_ai: ^2.0.0
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_dropzone: ^4.2.1
  http: ^1.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/