// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHLpg9nyQ2l79Yne_gtdMchb35nJrFIdM',
    appId: '1:83769187560:web:4f0e44c2000f3098807d5d',
    messagingSenderId: '83769187560',
    projectId: 'projeto-topicos-cf5ee',
    authDomain: 'projeto-topicos-cf5ee.firebaseapp.com',
    storageBucket: 'projeto-topicos-cf5ee.firebasestorage.app',
    measurementId: 'G-P3VWYM6WPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQpbH_9kczym1_69M0pEWWk6ZqpPsYFc8',
    appId: '1:83769187560:android:7f478533a249bb7a807d5d',
    messagingSenderId: '83769187560',
    projectId: 'projeto-topicos-cf5ee',
    storageBucket: 'projeto-topicos-cf5ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAqlwTlgQzCe4E4aMHVwk_osMoLOPEYD8',
    appId: '1:83769187560:ios:56ec5f37ac2ca3e8807d5d',
    messagingSenderId: '83769187560',
    projectId: 'projeto-topicos-cf5ee',
    storageBucket: 'projeto-topicos-cf5ee.firebasestorage.app',
    iosBundleId: 'com.example.projetoTopicos',
  );
}
